import Footer from "@/components/Footer"
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Header from "@/components/Header"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: 'shivank Tyagi',
    template: '%s | shivank',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="container-fluid">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
